### ISSUE TITLE
升级 ts2php，解决 typescript 版本的问题

### ISSUE THREAD

**Issue by harttle** [searchfe/san-ssr-target-php#32]
问题：旧版 ts2php 依赖了外部的 typescript，且强依赖特定版本。导致安装 san-ssr-target-php 时需要额外注意被 ts2php 使用到的 typescript，存在 dedupe 时情况会尤为复杂。

期望：目前 ts2php 已经不依赖外部 typescript，但需要升级 san-ssr-target-php 中依赖的 ts2php。

**Comment by shirookie** [comment]
2.2.2 已升级 ts2php@0.29.0
