### ISSUE TITLE
ssr 渲染后删除顶层 <template> 引入的 <div>

### ISSUE THREAD

**Issue by l5oo00** [searchfe/san-ssr-target-php#4]

**Comment by harttle** [comment]
其实初衷是把 san 作为模板引擎使用的场景下，不很 work。例如把所有 `<meta>` 放到一个子组件中引入到 `<head>` 里，期望不输出 `<template>` 生成的 `<div>`。接口上考虑以下几点：

* 向下兼容：新增接口 `noTemplateOutput`，默认值为 `false` 保持默认行为和旧版一样。
* 放在编译期（而非 `noDataOutput` 一样在运行时）：是否当作模板引擎用是一个技术选择，跟运行时数据应无关。
* 所有组件都生效：而非只有顶层组件生效，比如上述 `<head>`, `<meta>` 的例子。这意味着作为运行时参数比如 `render($noTemplateOutput)` 会很麻烦要逐级传递。
