### ISSUE TITLE
产出 ssr.php 中移除代码注释

### ISSUE THREAD

**Issue by harttle** [searchfe/san-ssr-target-php#8]
源码中存在代码注释是合理的；产出文件中的注释没有意义（版本、时间、版权等除外），还会（略微）增加运行时的 parse 代码的成本。

备选这个库：https://www.npmjs.com/package/strip-comments#api 因为注释只有 `//` 和 `/**/` 两种且来源可控（都是本代码库里写的），直接写个小状态机可能跑起来更快速。

**Comment by shirookie** [comment]
san-ssr-target-php@2.6.3

测试未产出注释
